# Generated by Django 3.2.17 on 2023-04-04 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField()),
                ('work_experience', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('price', models.IntegerField()),
                ('availability', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='')),
                ('description', models.TextField()),
                ('date_created', models.DateField()),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90, unique=True)),
                ('password', models.CharField(max_length=90)),
                ('type', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('gender', models.CharField(max_length=90)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=150)),
                ('post', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='customerArtworkReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('staus', models.CharField(max_length=90)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='artworkSellReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=90)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.artist')),
                ('awid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.artwork')),
            ],
        ),
        migrations.CreateModel(
            name='artworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staus', models.CharField(max_length=90)),
                ('awid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.artwork')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artapp.login'),
        ),
    ]
