from django.urls import path

from artapp import views

urlpatterns=[
    path('',views.main,name='main'),
    path('userReg',views.userReg,name='userReg'),
    path('usrRegistration',views.usrRegistration,name='usrRegistration'),
    path('log',views.log,name='log'),
    path('forgotPass',views.forgotPass,name='forgotPass'),
    path('password_reset',views.password_reset,name='password_reset'),
    path('logout',views.logout,name='logout'),
    ###### admin #########
    path('adminHome',views.adminHome,name='adminHome'),
    path('manageArtist',views.manageArtist,name='manageArtist'),
    path('addArtists',views.addArtists,name='addArtists'),
    path('addArtist',views.addArtist,name='addArtist'),
    path('updateArtist',views.updateArtist,name='updateArtist'),
    path('editArtist/<int:id>',views.editArtist,name='editArtist'),
    path('delArtist/<int:id>',views.delArtist,name='delArtist'),
    path('updtPriceAvailOfArtWork',views.updtPriceAvailOfArtWork,name='updtPriceAvailOfArtWork'),
    path('updatePriceAvail/<int:id>',views.updatePriceAvail,name='updatePriceAvail'),
    path('updPrAv',views.updPrAv,name='updPrAv'),
    path('viewCustomerOrder',views.viewCustomerOrder,name='viewCustomerOrder'),
    path('viewArtworkPutSale',views.viewArtworkPutSale,name='viewArtworkPutSale'),
    path('putForsale/<int:id>',views.putForsale,name='putForsale'),
    path('changePassword',views.changePassword,name='changePassword'),
    path('change_password',views.change_password,name='change_password'),
    path('orderFilter',views.orderFilter,name='orderFilter'),
    path('dateFilter',views.dateFilter,name='dateFilter'),
    ########## artist ########
    path('artistHome', views.artistHome, name='artistHome'),
    path('manageArtwork', views.manageArtwork, name='manageArtwork'),
    path('addArtwork', views.addArtwork, name='addArtwork'),
    path('add_artwork', views.add_artwork, name='add_artwork'),
    path('updateArtWork', views.updateArtWork, name='updateArtWork'),
    path('editArtwork/<int:id>', views.editArtwork, name='editArtwork'),
    path('viewArtwrkReqandUpdtStats', views.viewArtwrkReqandUpdtStats, name='viewArtwrkReqandUpdtStats'),
    path('acceptReq/<int:id>', views.acceptReq, name='acceptReq'),
    path('rejectReq/<int:id>', views.rejectReq, name='rejectReq'),
    path('srchOrdersApprvl', views.srchOrdersApprvl, name='srchOrdersApprvl'),
    path('srchOrderUser', views.srchOrderUser, name='srchOrderUser'),
    path('apprvOrder/<int:id>', views.apprvOrder, name='apprvOrder'),
    path('rejectOrder/<int:id>', views.rejectOrder, name='rejectOrder'),
    path('artwork_sell_req', views.artwork_sell_req, name='artwork_sell_req'),
    path('sellReq/<int:id>', views.sellReq, name='sellReq'),
    path('changeArtistPassword', views.changeArtistPassword, name='changeArtistPassword'),
    path('change_Artist_password', views.change_Artist_password, name='change_Artist_password'),
    ########## user ########
    path('userHome', views.userHome, name='userHome'),
    path('addWorkReq', views.addWorkReq, name='addWorkReq'),
    path('sentWorkReq', views.sentWorkReq, name='sentWorkReq'),
    path('sent_work_req', views.sent_work_req, name='sent_work_req'),
    path('viewArtworkAndorder', views.viewArtworkAndorder, name='viewArtworkAndorder'),
    path('order/<int:id>', views.order, name='order'),
    path('purchase/<int:id>', views.purchase, name='purchase'),
    path('viewArtworkAndPurchase', views.viewArtworkAndPurchase, name='viewArtworkAndPurchase'),
    path('changeUserPassword', views.changeUserPassword, name='changeUserPassword'),
    path('change_user_password', views.change_user_password, name='change_user_password'),

]